src/app/background.ts

fix: Support secure access URLs

---

src/app/background.ts
src/manifest.json

feat: Support US and China region

---

src/app/components/marktone.tsx
src/app/kintone/kintone-client.ts

fix: Fix to be able to upload a file on the notification page

---

src/app/content.tsx

fix: Fix to insert a mention into record comments when replying

---

src/styles/content.scss

fix: Fix an autocomplete UI is hidden in app record comment

---

src/app/markdown/renderer/marktone-renderer.ts

fix: Fix a strikethrough not to be removed

---

src/app/kintone/kintone-client.ts

feat: Support Guest space

---

src/styles/content.scss

#26 prevents the sidebar of app record from scrolling.
refs #5

fix: Fix sidebar of app record not scrolling

---

package-lock.json
package.json

https://www.npmjs.com/advisories/961

chore: Upgrade node-sass to 4.13.1

---

src/app/background.ts
src/app/content.tsx
src/app/marktone-config.ts
src/manifest.json

feat: Persist Marktone enabled status to Chrome storage

---

src/app/markdown/renderer/marktone-renderer.ts

fix: Fix broken indentation in checklist

---

package-lock.json

fix(deps): Update elliptic to v6.5.4

---

src/app/components/marktone.tsx
src/manifest.json

feat: Implement the feature to upload files from the clipboard

---

src/app/components/marktone.tsx

fix: Fix to limit file upload function from clipboard to only supported pages

---

src/app/markdown/renderer/marktone-renderer.ts

https://github.com/highlightjs/highlight.js/issues/2277

fix: Migrate to highlight.js's new API

---

.circleci/config.yml

chore(ci): Update Node.js to v16.0.0 on CI

---

package-lock.json

[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at node_modules/postcss/package.json.
https://github.com/postcss/postcss/commit/96faacb974dcc5c3ff17c97e16785abcbea410d2

chore(deps): Update postcss to v8.2.12

---

package-lock.json

fix(deps): Update browserslist to v4.16.6

---

package-lock.json
package.json
src/app/background.ts
src/app/content.tsx
src/initialization.js
src/manifest.json
webpack.config.js

Migrate to manifest v3

---

.storybook/main.js
.storybook/preview.js
.storybook/preview.scss
package-lock.json
package.json
src/app/components/MarkdownEditor.tsx
src/app/components/MarkdownPreview.tsx
src/app/components/MarktoneProvider.stories.tsx
src/app/components/MarktoneProvider.tsx
src/app/hooks/useMarkdown.tsx
src/app/utils/convertMarkdownToReact.ts
src/app/utils/rehypeCustomStyle.ts
src/app/utils/rehypeInlineHighlight.ts

feat: Add MarkdownEditor component

---

src/app/marktone-handler.tsx

https://reactjs.org/link/switch-to-createroot

refactor: Use createRoot instead of ReactDOM.render

---

src/app/components/marktone.tsx
src/app/kintone/directory-entity.ts
src/app/kintone/kintone-client.ts
src/app/markdown/replacer/mention-replacer.ts

fix: fix the mention of a guest that is not working properly
